project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - materialy.qmd
    - jak-pracovat-s-materialy.qmd
    - vyucujici.qmd
    - archiv.qmd
    - o-kurzu.qmd
    - zacnete.qmd
    - rozvrh.qmd
    - zdroje.qmd
    - hodnoceni.qmd
    - semestry/*/index.qmd
    - semestry/*/rozvrh.qmd
    - semestry/*/hodnoceni.qmd
    - semestry/*/vyucujici.qmd
    - semestry/*/*/index.qmd
    - rok/*/index.qmd
    - rok/*/*/index.qmd

lang: cs

website:
  title: "Biostatistika"
  description: "Studijní materiály ke kurzu Biostatistika a plánování ekologických pokusů (MB120P163)"
  site-url: "https://cuni-natur-biostatistics.github.io"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Aktuální semestr
        menu:
          - href: materialy.qmd
            text: Materiály
          - href: rozvrh.qmd
            text: Rozvrh
          - href: hodnoceni.qmd
            text: Závěrečné hodnocení
      - href: jak-pracovat-s-materialy.qmd
        text: Jak pracovat s materiály
      - href: archiv.qmd
        text: Archiv
      - href: vyucujici.qmd
        text: Vyučující
    right:
      - href: https://cuni-natur-biostatistics.github.io/slovnik/
        text: Slovník pojmů

format:
  html:
    theme:
      - cosmo
      - assets/brand/brand_theme.scss
      - assets/styles.scss
    include-in-header:
      - assets/brand/fonts-include.html
    include-after-body:
      - assets/footer.html
    toc: false
    link-external-newwindow: true

execute:
  freeze: false
